services:
  postgres:
    image: postgres:16
    container_name: books_postgres
    restart: always
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d booksdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bookmate_app
    restart: always
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: booksdb
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    ports:
      - "7860:7860"
    volumes:
      - ./DATA:/app/DATA
      - ./INDEXES:/app/INDEXES
      - ./src:/app/src
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy

volumes:
  qdrant_data: {}
  pgdata:
    driver: local
