services:
  postgres:
    image: postgres:16
    container_name: books_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: booksdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build: .
    container_name: bookmate_app
    restart: always
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: booksdb
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    ports:
      - "7860:7860"
    volumes:
      - ./DATA:/app/DATA
      - ./INDEXES:/app/INDEXES
      - ./src:/app/src
    depends_on:
      - postgres
      - qdrant

volumes:
  qdrant_data: {}
  pgdata:
    driver: local
